# Generated by Django 6.0 on 2025-12-08 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0003_prioridad_sla_horas_alter_prioridad_nivel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Pregunta o título del artículo', max_length=255)),
                ('problema', models.TextField(help_text='Descripción detallada del problema')),
                ('solucion', models.TextField(help_text='Solución paso a paso')),
                ('tags', models.CharField(blank=True, help_text='Palabras clave separadas por comas (ej: password, acceso, vpn)', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('publicado', models.BooleanField(default=True, help_text='Si está visible para usuarios')),
                ('destacado', models.BooleanField(default=False, help_text='Aparece en artículos destacados')),
                ('vistas', models.IntegerField(default=0, help_text='Número de veces que se ha visto')),
                ('util_si', models.IntegerField(default=0, help_text="Votos positivos '¿Fue útil? Sí'")),
                ('util_no', models.IntegerField(default=0, help_text="Votos negativos '¿Fue útil? No'")),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoría del artículo (mismas que tickets)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_faq', to='tickets.categoria')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artículo FAQ',
                'verbose_name_plural': 'Artículos FAQ',
                'ordering': ['-destacado', '-fecha_actualizacion'],
            },
        ),
    ]
