# Generated by Django 6.0 on 2025-12-08 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(choices=[('si', 'Útil'), ('no', 'No útil')], max_length=2)),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='knowledge_base.articulofaq')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_faq', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto FAQ',
                'verbose_name_plural': 'Votos FAQ',
                'ordering': ['-fecha_voto'],
                'unique_together': {('usuario', 'articulo')},
            },
        ),
    ]
