# Generated by Django 6.0 on 2025-12-08 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_votofaq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Imagen o PDF para ilustrar el artículo', upload_to='faq_archivos/%Y/%m/')),
                ('descripcion', models.CharField(help_text="Descripción del paso (ej: 'Paso 1: Click en configuración')", max_length=200)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='knowledge_base.articulofaq')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_faq_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo FAQ',
                'verbose_name_plural': 'Archivos FAQ',
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
    ]
