# Generated by Django 5.2.9 on 2025-12-03 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_managers_alter_usuario_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tecnico',
            old_name='disponible',
            new_name='activo',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='calificacion_promedio',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='carga_trabajo_actual',
        ),
        migrations.AddField(
            model_name='tecnico',
            name='nivel_experiencia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='accounts.rol'),
        ),
    ]
