# Generated by Django 6.0 on 2025-12-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_disponible_tecnico_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.CharField(choices=[('👤', '👤 Persona'), ('👨', '👨 Hombre'), ('👩', '👩 Mujer'), ('🧑', '🧑 Persona neutra'), ('👔', '👔 Profesional'), ('💼', '💼 Ejecutivo'), ('🎓', '🎓 Estudiante'), ('⚙️', '⚙️ Técnico')], default='👤', help_text='Ícono de perfil personalizado', max_length=10),
        ),
    ]
