# Generated by Django 5.2.9 on 2025-12-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_categoria_alter_ticket_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioridad',
            name='sla_horas',
            field=models.PositiveIntegerField(blank=True, help_text='Horas objetivo de resolución para esta prioridad.', null=True),
        ),
        migrations.AlterField(
            model_name='prioridad',
            name='nivel',
            field=models.PositiveSmallIntegerField(default=2, help_text='1=Baja, 2=Media, 3=Alta, 4=Crítica (o similar).'),
        ),
    ]
