# Generated by Django 6.0 on 2025-12-09 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_comentarioticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], help_text='Calificación de 1 a 5 estrellas')),
                ('resuelto', models.BooleanField(help_text='¿El problema fue resuelto?')),
                ('comentario', models.TextField(blank=True, help_text='Comentario adicional sobre la atención (opcional)')),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(help_text='Ticket calificado (relación 1 a 1)', on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='tickets.ticket')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la calificación', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación de Ticket',
                'verbose_name_plural': 'Calificaciones de Tickets',
                'ordering': ['-fecha_calificacion'],
            },
        ),
    ]
