# Generated by Django 6.0 on 2025-12-09 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        ('tickets', '0005_calificacionticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tickets.ticket'),
        ),
    ]
